# Tutorial Objectives:

Creation of array is one thing and indexing is another factors that makes numpy so flexible. In this section we will cover

1. Basics Indexing
2. Dimensional Indexing tools
3. Advanced Indexing
4. Field Access
5. Assigning values to indexed arrays
6. Dealing with variable numbers of indices within programs
   

In [1]:
import numpy as np

## 1. Introduction

`ndarrays` can be indexed using the standard Python`x[obj]` syntax where x is the array and obj is the selection. There are different kinds of indexing available depending on objc: basics indexing, advanced indexing and field access.

## 2. Basic Indexing

### 1. Single element indexing

Single element indexing works exactly like that for other standard python sequences. It is `0-based` and accepts negative indices for indexing from the end of the array.


In [4]:
x = np.arange(10)

In [6]:
print(x[2])

2


In [7]:
print(x[-2])

8


It is not necessary to separate each dimension’s index into its own set of square brackets.

In [9]:
x = x.reshape((2,5))
print(x[1,3])

8


In [10]:
print(x[1,-2])

8


Note that if one indexes a multidimensional array with fewer indices than dimensions, one gets a subdimensional array. For example:

In [11]:
print(x[0])

[0 1 2 3 4]


That is, each index specified selects the array corresponding to the rest of the dimensions selected. In the above example, choosing 0 means that the remaining dimension of length 5 is being left unspecified, and that what is returned is an array of that dimensionality and size. It must be noted that the returned array is a view, i.e., it is not a copy of the original, but points to the same values in memory as does the original array. In this case, the 1-D array at the first position (0) is returned. So using a single index on the returned array, results in a single element being returned. That is:

print(x[0][2])

### 2. Slicing and Striding

Basics slicing extends Pythons basic concept of slicing to N dimensions. Basic slicing occurs when *obj* is a `slice` objects(constructed by `start:stop:stop` notation inside the brackets) , an integer or a tuple of slice objects and in tegers.

All arrays generated by the basic slicing are always `views` of the original array.

>**Note**:
>NumPy slicing creates a view instead of a copy as in the case of built-in Python sequences such as string, tuple and list. Care must be taken when extracting a small portion from a large array which becomes useless after the extraction, because the small portion extracted contains a reference to the large original array whose memory will not be released until all arrays derived from it are garbage-collected. In such cases an explicit `copy()` is recommended.

The standard rules of sequences slicing apply to basic slicing on a per-dimension baisccs . Some useful concepts to remember include:

-  The basic syntax is `i:j:k` where *i* is the starting index , *j* is the stop index and *k* is the. step index ($k \neq 0$)

In [13]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x[1:7:2])

[1 3 5]


- Negative `i` and `j` are interpreted as `n + i` and `n + j` where `n` is the number of elements in the corresponding dimension. Negative k makes stepping go towards smaller indices. From the above example:

In [15]:
print(x[-2:10])


[8 9]


In [17]:
print(x[-3:3:-1])

[7 6 5 4]


- Assume `n` is the number of elements in the dimension being sliced. Note that `::` is the same as `:` and means select all indices along this axis. From the above example:

In [19]:
print(x[:5])

[0 1 2 3 4]


In [20]:
print(x[::])

[0 1 2 3 4 5 6 7 8 9]
